executable = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/stepchain_2018.sh 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
MyIndex=$(ProcId)+1000
Extention=$INT(MyIndex,%d)
arguments = "scout_$(Extention).root 2018/ScoutingRunD/ScoutingCaloMuon/crab_20200617_174740/200617_154747/0001/ 2018D2"
universe = vanilla
queue 286
#log = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).log
#output = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).out
#error = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).err
+JobFlavour = "espresso"
#queue INPUT from data17Dlist.list
#queue INPUT from lousyList3.list


# or
# queue INPUT in (
# file1
# file2
# file3
# ..
# )
