executable = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/addmva.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
universe = vanilla
output = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/submit/addmva/hide/log/log_$(Process).out
error =/afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/submit/addmva/hide/log/log_$(Process).err
log = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/submit/addmva/hide/log/log_$(Process).log
queue arguments from (
    "tree_188.root   2018A  2018"
    "tree_257.root   2018A  2018"
    "tree_714.root   2018D1  2018"
)
+JobFlavour = "microcentury"
