executable = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/fulljob.sh 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
arguments = "scout_$(ProcId).root 2017/ScoutingRunF/ScoutingCaloMuon/crab_20200617_140425/200617_120436/0000/ 2017F 4"
universe = vanilla
queue 589
#log = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).log
#output = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).out
#error = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).err
+JobFlavour = "espresso"
#queue INPUT from data17Dlist.list
#queue INPUT from lousyList3.list


# or
# queue INPUT in (
# file1
# file2
# file3
# ..
# )
