executable = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/fulljob.sh 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
arguments = "scout_$(ProcId).root 2018/ScoutingRunA/ScoutingCaloMuon/crab_20200617_174717/200617_154725/0000/ 2018A 5"
universe = vanilla
queue 582
+JobFlavour = "espresso"


# or
# queue INPUT in (
# file1
# file2
# file3
# ..
# )
