executable = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/fulljob_mc.sh 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
arguments = "scout_$(ProcId).root 2018/MCDY2018LowMass/DarkPhoton/crab_20200706_185414/200706_165513/0000/ MC"
universe = vanilla
queue 95
#log = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).log
#output = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).out
#error = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(Process).err
+JobFlavour = "espresso"
#queue INPUT from data17Dlist.list
#queue INPUT from lousyList3.list


# or
# queue INPUT in (
# file1
# file2
# file3
# ..
# )
