executable = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/macros/thejob_noid.sh 
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ""
transfer_output_files = ""
arguments = "tree_$(ProcId).root 2018B"
universe = vanilla
queue 266
#log = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(ProcId).log
#output = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(ProcId).out
#error = /afs/cern.ch/work/w/wangz/DarkPhotonAnalysisV2/DimuonAnalysis/log/test1.$(ProcId).err
+JobFlavour = "workday"
#queue INPUT from data17Dlist.list
#queue INPUT from lousyList3.list


# or
# queue INPUT in (
# file1
# file2
# file3
# ..
# )
